#!/usr/bin/env python3
"""Check local manual links, heading anchors, Bash syntax, and registry drift.

No documented commands are executed and no external links are fetched.
--write-generated refreshes only the derived predictor reference.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
FENCES = re.compile(r"^([ \t]*)(`{3,}|~{3,})([^\n]*)\n(.*?)^\1\2[ \t]*$", re.M | re.S)
LINKS = re.compile(r"!?\[[^\]\n]*\]\((<[^>]+>|[^\s)]+)(?:\s+\"[^\"]*\")?\)")


def without_fences(content: str) -> str:
    # Preserve line numbers for useful diagnostics.
    return FENCES.sub(lambda match: "\n" * match.group().count("\n"), content)


def anchors(content: str) -> set[str]:
    seen: Counter[str] = Counter()
    result = set(re.findall(r'<a\s+(?:id|name)=["\']([^"\']+)', content))
    for heading in re.findall(r"^#{1,6}\s+(.+?)\s*#*\s*$", without_fences(content), re.M):
        heading = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", heading)
        slug = re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")
        count = seen[slug]
        seen[slug] += 1
        result.add(f"{slug}-{count}" if count else slug)
    return result


def check_file(path: Path) -> list[str]:
    content = path.read_text(encoding="utf-8")
    errors = []
    clean = without_fences(content)
    for match in LINKS.finditer(clean):
        url = urlsplit(match.group(1).strip("<>"))
        if url.scheme or url.netloc:
            continue
        target = (path.parent / unquote(url.path)).resolve() if url.path else path
        line = clean.count("\n", 0, match.start()) + 1
        if not target.exists():
            errors.append(f"{path}:{line}: missing link target {match.group(1)}")
        elif url.fragment and target.suffix == ".md" and unquote(url.fragment) not in anchors(target.read_text(encoding="utf-8")):
            errors.append(f"{path}:{line}: missing heading {match.group(1)}")
    for match in FENCES.finditer(content):
        if match.group(3).strip() not in {"bash", "sh"}:
            continue
        result = subprocess.run(["bash", "-n"], input=match.group(4), text=True, capture_output=True)
        if result.returncode:
            line = content.count("\n", 0, match.start()) + 1
            errors.append(f"{path}:{line}: shell syntax: {result.stderr.strip()}")
    # Do not print the sensitive match itself in CI logs.
    if re.search(r"https?://(?:data\.omim\.org/downloads/|dist\.genos\.us/academic/|geniadb\.org/(?:downloads/download|variant/vcf/))", content, re.I):
        errors.append(f"{path}: private/restricted direct dataset URL; remove it")
    return errors


def predictor_reference(registry: dict) -> str:
    annotators = {row["id"]: row for row in registry["annotators"]}
    lines = [
        "---", 'title: "Generated predictor reference"', "parent: Reference", "nav_order: 18", "---", "",
        "# Generated predictor reference", "",
        "<!-- GENERATED by scripts/check_documentation.py --write-generated; do not edit. -->", "",
        "This table mirrors the registered annotation contract, not installed availability,",
        "UI toggle defaults, or a claim that every source is in the regression panel.",
        "Metric fields include provenance as well as scores. For protein-match postprocessors,",
        "the registered scope describes emitted allele observations; their internal source",
        "comparison also checks gene/transcript/protein coordinates. See",
        "[Predictor architecture](PREDICTOR_ARCHITECTURE.md) and",
        "[annotation sources](ANNOTATIONS.md) for interpretation and matching details.", "",
        "| Predictor | Resource ID | Registered scope | Fields |", "|---|---|---|---|",
    ]
    for predictor in registry["predictors"]:
        annotator = annotators[predictor["annotator_id"]]
        fields = ", ".join(f'`{metric["field"]}`' for metric in predictor["metrics"])
        lines.append(f'| {predictor["label"]} | `{predictor["resource_id"]}` | `{annotator["match"]["scope"]}` | {fields} |')
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-generated", action="store_true")
    args = parser.parse_args()
    registry = json.loads((ROOT / "config/predictor-registry.json").read_text(encoding="utf-8"))
    generated = ROOT / "docs/PREDICTOR_REFERENCE.md"
    expected = predictor_reference(registry)
    if args.write_generated:
        generated.write_text(expected, encoding="utf-8")
    errors = []
    if not generated.exists() or generated.read_text(encoding="utf-8") != expected:
        errors.append("Predictor reference is stale: python3 scripts/check_documentation.py --write-generated")
    paths = sorted((ROOT / "docs").rglob("*.md"))
    paths += [ROOT / name for name in ("README.md", "config/README.md", "desktop/README.md", "webui/README.md", "docker/README.md")]
    for path in paths:
        errors.extend(check_file(path))
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    print(f"Documentation checks passed: {len(paths)} Markdown files, local links/anchors, Bash syntax, and generated predictor reference.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
