import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);

test("is configured as a loopback-only local application", async () => {
  const packageJson = JSON.parse(await readFile(new URL("package.json", root), "utf8"));
  assert.match(packageJson.scripts.dev, /next dev --hostname 127\.0\.0\.1/);
  assert.match(packageJson.scripts.start, /next start --hostname 127\.0\.0\.1/);
  await assert.rejects(readFile(new URL(".openai/hosting.json", root), "utf8"));
});

test("keeps the clinical review defaults visible", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  assert.match(source, /useState<VariantRow\[\]>\(\[\]\)/);
  assert.doesNotMatch(source, /demoVariants/);
  assert.match(source, /Clinical transcripts \(MANE \+ PICK fallback\)/);
  assert.match(source, /Exclude RepeatMasker/);
  assert.match(source, /Exclude SegDup/);
  assert.match(source, /ClinVar P \/ LP only/);
  assert.match(source, /Candidate compound het/);
});

test("provides separate local annotation and annotated-VCF review paths", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  const service = await readFile(new URL("app/local-service.ts", root), "utf8");
  assert.match(source, /useState<View>\("import"\)/);
  assert.match(source, /pendingFiles\.length \? "review" : "annotate"/);
  assert.match(source, /Run VEP first/);
  assert.match(source, /Review annotated VCF/);
  assert.match(source, /Drop \.vcf or \.vcf\.gz files here/);
  assert.match(source, /Gzip and BGZF-compressed VCFs/);
  assert.match(source, /const VCF_FILE_ACCEPT = "[^"]*\.gz[^"]*application\/gzip/);
  assert.match(source, /accept=\{VCF_FILE_ACCEPT\}/);
  assert.match(source, /Annotation datasets/);
  assert.match(source, /Exome region only/);
  assert.match(source, /Whole genome/);
  assert.match(source, /analysisScope === "whole_genome"/);
  assert.match(source, /DEFAULT_WGS_ANNOTATION_SOURCES = new Set\(\["cadd_wgs", "promoterai"\]\)/);
  assert.equal(source.match(/annotationSourceIsEnabled\(source, analysisScope, sourceEnabled\)/g)?.length, 2);
  assert.match(source, /CADD and promoterAI on by default/);
  assert.match(source, /Indexing and prefiltering WGS/);
  assert.match(source, /Whole-genome indexing and prefiltering progress/);
  assert.match(source, /PASS\/QC AND \(popmax ≤ threshold OR popmax unavailable\)/);
  assert.match(source, /wgsImportJob\.records_scanned/);
  assert.match(await readFile(new URL("app/vcf.ts", root), "utf8"), /async function\* fileLines/);
  assert.doesNotMatch(await readFile(new URL("app/vcf.ts", root), "utf8"), /decoded\.join/);
  assert.match(source, /gnomAD popmax ≤/);
  assert.match(source, /\|promoterAI\| ≥/);
  assert.match(source, /ENCODE cCRE regions/);
  assert.match(source, /All noncoding regions/);
  assert.match(source, /No additional noncoding regions/);
  assert.doesNotMatch(source, /leaving CADD blank disables CADD/);
  assert.match(source, /PASS records only/);
  assert.match(source, /not read yet/);
  assert.match(source, /Import and review variants/);
  assert.match(source, /onImportFiles\(pendingFiles, analysisScope, submittedWgsFilters, activeWgsPaths, \{ keep:/);
  assert.match(source, /Recommended for very large files: use existing workstation paths/);
  assert.match(source, /Input genome build/);
  assert.match(source, /useState<"GRCh38" \| "GRCh37" \| "auto">\("auto"\)/);
  assert.match(source, /Detected .* logical CPU threads/);
  assert.match(source, /Use automatic/);
  assert.match(source, /Validated annotation bundle · VEP 113 \/ GRCh38/);
  assert.match(source, /intentionally pinned/);
  assert.doesNotMatch(source, /Check for updates/);
  assert.doesNotMatch(service, /\/api\/references\/update/);
  assert.doesNotMatch(source, /Annotation config/);
  assert.match(service, /annotation_options/);
  assert.match(service, /annotation-files\/stage/);
  assert.match(service, /\/api\/wgs-review/);
  assert.match(service, /getWgsReviewJob/);
  assert.match(service, /http:\/\/127\.0\.0\.1:43117/);
});

test("provides a persistent Sample Library, stable identity mapping, and storage controls", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  const service = await readFile(new URL("app/local-service.ts", root), "utf8");
  assert.match(source, />Sample library</);
  assert.match(source, /Keep in Sample Library/);
  assert.match(source, /Review once/);
  assert.match(source, /Include qualifying variants in Cohort Search/);
  assert.doesNotMatch(source, /Optional sequencing metadata/);
  assert.doesNotMatch(source, /Capture kit \/ assay/);
  assert.doesNotMatch(source, /Target BED path/);
  assert.match(source, /Who does .* belong to/);
  assert.match(source, /Link existing individual/);
  assert.match(source, /Phenotype unavailable for now/);
  assert.match(source, /Included in Cohort Search/);
  assert.match(source, /Add to Cohort Search/);
  assert.match(source, /Repair Cohort Search/);
  assert.match(source, /More actions/);
  assert.match(source, /Rebuild search index/);
  assert.match(source, /Remove from Cohort Search/);
  assert.doesNotMatch(source, /Refresh cohort index/);
  assert.match(service, /cohort_index_status/);
  assert.match(service, /cohort\/remove/);
  assert.match(source, /setView\("variants"\); setSelected\(null\)/);
  assert.match(source, /Build full WGS index/);
  assert.match(source, /Advanced full index/);
  assert.match(source, /Assay and import profile filters/);
  assert.match(source, /not interpreted as negative|not evidence that the individual lacks a variant/);
  assert.match(source, />Storage</);
  assert.match(source, /Clean temporary data/);
  assert.match(source, /Compact database/);
  assert.match(service, /\/api\/sample-library/);
  assert.match(service, /\/api\/storage/);
  assert.doesNotMatch(source, /cohort allele frequency/i);
});

test("provides annotation dataset setup and constrained local downloads", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  const service = await readFile(new URL("app/local-service.ts", root), "utf8");
  assert.match(source, /Set up annotation datasets/);
  assert.match(source, /Registration and setup instructions/);
  assert.match(source, /Download \/ resume/);
  assert.match(source, /Download \/ resume 83 GiB/);
  assert.match(service, /"cadd_wgs"/);
  assert.match(source, /Download latest/);
  assert.match(source, /Configured location/);
  assert.match(source, /downloadJob\.progress/);
  assert.match(service, /\/api\/resource-downloads/);
  assert.match(service, /startResourceDownload/);
  assert.match(source, /Prepare local files/);
  assert.match(source, /promoterAI_tss500\.tsv\.gz/);
  assert.match(service, /\/api\/resource-preparations\/promoterai/);
  assert.match(service, /startPromoterAiPreparation/);
  assert.match(source, /PromoterAI \|score\| ≥/);
  assert.match(source, /Math\.abs\(row\.promoterAI\) < promoterAbsMin/);
  assert.match(source, /Existing LoGoFunc \.csv\.gz file or containing folder/);
  assert.match(source, /Use existing source/);
  assert.match(service, /\/api\/resource-preparations\/logofunc/);
  assert.match(service, /startLoGoFuncPreparation/);
  assert.match(source, /LoGoFunc predicted class/);
});

test("builds compound-het candidates only from rows surviving active filters", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  assert.match(source, /candidateCompoundHetKeys\(screenFilteredRows\)/);
  assert.doesNotMatch(source, /candidateCompoundHetKeys\(rows\)/);
});

test("keeps SCREEN observed context separate and exposes defensible positive-evidence filtering", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  const regulatory = await readFile(new URL("app/regulatory-evidence.tsx", root), "utf8");
  const service = await readFile(new URL("app/local-service.ts", root), "utf8");
  assert.match(source, /Regulatory evidence/);
  assert.match(source, /RegulatoryFilterControl/);
  assert.match(source, /mode: "any"/);
  assert.match(regulatory, /SCREEN observed/);
  assert.match(regulatory, /Element–gene links · to be developed/);
  assert.match(regulatory, /Gene-specific variant-effect prediction · to be developed/);
  assert.doesNotMatch(regulatory, /Gene links · not installed/);
  assert.match(source, /reviewAnalysisScope === "whole_genome"/);
  assert.match(source, /analysisScope === "whole_genome" && reviewSection === "regulatory"/);
  assert.match(source, /analysisScope === "whole_genome" && <RegulatorySummary/);
  assert.ok(source.indexOf("RawVcfEvidencePanel evidence={selected.rawVcfEvidence}") < source.indexOf("analysisScope === \"whole_genome\" && <RegulatorySummary"));
  assert.match(regulatory, /item\.state_label/);
  assert.match(regulatory, /classification unavailable/);
  assert.match(regulatory, /Classifier assays/);
  assert.match(regulatory, /Require positive SCREEN evidence/);
  assert.match(regulatory, />Immune context</);
  assert.match(regulatory, /any immune-related tissue aggregate or curated immune-cell context/);
  assert.match(regulatory, /setActiveSetId\(immuneAll\.id\)/);
  assert.match(regulatory, /Other context filters/);
  assert.match(regulatory, /any selected tissue or cell context has positive evidence/);
  assert.doesNotMatch(regulatory, /Selected contexts must match/);
  assert.doesNotMatch(regulatory, /<option value="all">ALL/);
  assert.match(regulatory, /Manage named context sets/);
  assert.match(regulatory, /Display context set/);
  assert.match(regulatory, /assign a target gene/);
  assert.match(regulatory, /Why are both coding and regulatory annotations shown/);
  assert.match(regulatory, /same gene, another gene, or multiple genes/);
  assert.match(service, /\/api\/screen-context\/catalog/);
  assert.match(service, /\/api\/screen-context\/filter/);
});

test("provides a full variant review workspace with configurable evidence", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(source, /review-workspace/);
  assert.match(source, /Information shown/);
  assert.match(source, /AlphaMissense/);
  assert.match(source, /CADD phred/);
  assert.match(source, /SpliceAI max/);
  assert.match(source, /promoterAI/);
  assert.match(source, /CADD raw/);
  assert.match(source, /GERP\+\+ RS/);
  assert.match(source, /phyloP 100-way/);
  assert.match(source, /phastCons 100-way/);
  assert.match(source, /All gnomAD population frequencies/);
  assert.match(source, /Loaded automatically from bundled gnomAD/);
  assert.match(source, /ENCODE SCREEN cCRE/);
  assert.match(source, /Does not overlap a/);
  assert.match(source, /proximity is not a target-gene assignment/);
  assert.match(source, /Every gene below is listed only because its gene-level TSS lies within/);
  assert.match(source, /simultaneously have a transcript-specific coding consequence and be a regulatory element/);
  assert.match(source, /same gene, another gene, or multiple genes/);
  assert.match(source, /Include non-protein-coding genes/);
  assert.match(source, /Protein-coding genes are shown by default/);
  assert.match(source, /shown ·.*total.*protein-coding.*other/);
  assert.match(source, /Distance from cCRE to TSS/);
  assert.match(await readFile(new URL("app/local-service.ts", root), "utf8"), /\/api\/ccre-context/);
  assert.match(source, /loadBundledReferences/);
  assert.match(styles, /\.workspace\.review-mode/);
  assert.match(styles, /\.review-list/);
  assert.match(styles, /\.review-detail/);
  assert.match(styles, /\.review-detail \{[^}]*min-height: 0;[^}]*overflow-y: auto/);
  assert.match(styles, /\.review-workspace \{[^}]*min-height: 0;[^}]*overflow: hidden/);
  assert.match(source, /detailRef\.current\?\.scrollTo\(\{ top: 0 \}\)/);
});

test("uses editable gene sets and compact coordinate-based variant IDs", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  assert.match(source, /IEI haploinsufficiency/);
  assert.match(source, /type View = .*"gene_lists"/);
  assert.match(source, />Gene lists</);
  assert.match(source, /Custom gene lists/);
  assert.match(source, /Create list/);
  assert.match(source, /Upload list/);
  assert.match(source, /CUSTOM_GENE_LISTS_STORAGE_KEY/);
  assert.match(source, /customLists\.map/);
  assert.match(source, /Restore bundled list/);
  assert.match(source, /Changes remain on this workstation/);
  assert.match(source, /LoF constrained/);
  assert.match(source, /pLI ≥ 0\.9 or LOEUF/);
  assert.match(source, /`\$\{row\.chrom\}:\$\{row\.pos\}:\$\{row\.ref\}:\$\{row\.alt\}`/);
  assert.match(source, /compactAllele/);
  assert.doesNotMatch(source, /row\.pos\.toLocaleString\(\).*row\.ref/);
});

test("provides persistent genotype-first cohort indexing and carrier search", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  const service = await readFile(new URL("app/local-service.ts", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(source, /Genotype-first discovery/);
  assert.match(source, /Index annotated VCFs/);
  assert.match(source, /Exact variant/);
  assert.match(source, /Qualifying variants in gene/);
  assert.match(source, /Find carriers/);
  assert.match(source, /I confirm header-ambiguous VCFs are GRCh38/);
  assert.match(service, /\/api\/cohort\/import/);
  assert.match(service, /\/api\/cohort\/import-jobs/);
  assert.match(source, /startCohortImport/);
  assert.match(source, /role="progressbar"/);
  assert.match(source, /records scanned/);
  assert.match(service, /\/api\/cohort\/query/);
  assert.match(service, /\/api\/cohort\/samples/);
  assert.match(service, /\/api\/cohort\/variant-detail/);
  assert.match(service, /\/api\/cohort\/review-records/);
  assert.match(service, /\/api\/cohort\/sample-review/);
  assert.match(source, /Manage cohort samples/);
  assert.match(source, /Remove selected/);
  assert.match(source, /unique variant/);
  assert.match(source, /Matched carriers/);
  assert.match(source, /Review selected findings/);
  assert.match(source, /LOAD SELECTED INDIVIDUALS/);
  assert.match(source, /REVIEW THIS VARIANT/);
  assert.match(source, /Complete stored review sets were loaded using each source's original cohort import profile/);
  assert.match(source, /Full source INFO, VEP CSQ, and sample FORMAT annotations were loaded on demand/);
  assert.match(source, /All source VCF annotations/);
  assert.match(source, /Variant details/);
  assert.match(source, /Compact WGS/);
  assert.match(source, /Compact WGS candidate import/);
  assert.match(source, /Source variant scope/);
  assert.match(source, /This provenance label controls whether regulatory evidence is available/);
  assert.match(source, /Full WGS index/);
  assert.match(service, /analysis_scope/);
  assert.match(source, /selected noncoding region route/);
  assert.match(source, /prefilter_records_retained/);
  assert.match(styles, /\.workspace\.cohort-mode/);
  assert.match(styles, /\.cohort-table/);
  assert.match(styles, /\.cohort-variant-table/);
  assert.match(styles, /\.cohort-variant-detail/);
  assert.match(styles, /\.cohort-sample-manager/);
});

test("provides pedigree-aware de novo and compound-heterozygous review", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  const parser = await readFile(new URL("app/vcf.ts", root), "utf8");
  const trio = await readFile(new URL("app/trio.ts", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(source, /Family analysis/);
  assert.match(source, /Upload PED/);
  assert.match(source, /High-confidence de novo/);
  assert.match(source, /Parental relationships confirmed/);
  assert.match(source, /Both variants pass active filters/);
  assert.match(source, /Trio genotypes/);
  assert.match(parser, /sampleGenotypes/);
  assert.match(parser, /phaseHaplotype/);
  assert.match(trio, /confirmed_trans_inheritance/);
  assert.match(trio, /possible_parental_mosaicism/);
  assert.match(styles, /\.family-page/);
  assert.match(styles, /\.trio-table/);
});

test("provides local manual and mapped spreadsheet phenotype intake", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  const service = await readFile(new URL("app/local-service.ts", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(source, /Demographics & phenotypes/);
  assert.match(source, /Manual entry/);
  assert.match(source, /Spreadsheet import/);
  assert.match(source, /Reported race/);
  assert.match(source, /Reported ethnicity/);
  assert.match(source, /No HPO inference or phenotype-based variant ranking/);
  assert.match(source, /CSV, TSV, or XLSX/);
  assert.match(source, /Preserve unmapped columns as custom fields/);
  assert.match(service, /\/api\/phenotypes\/preview/);
  assert.match(service, /\/api\/phenotypes\/validate/);
  assert.match(service, /\/api\/phenotypes\/import/);
  assert.match(styles, /\.workspace\.phenotype-mode/);
  assert.match(styles, /\.mapping-grid/);
});

test("links phenotype records from a dedicated variant-review tab", async () => {
  const source = await readFile(new URL("app/VariantWorkbench.tsx", root), "utf8");
  const service = await readFile(new URL("app/local-service.ts", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(source, /reviewSection === "phenotype"/);
  assert.match(source, />Phenotype<\/button>/);
  assert.match(source, /PhenotypeReviewPanel/);
  assert.match(source, /getPhenotypesBySample\(sample\)/);
  assert.match(service, /normalizePhenotypeIndividual/);
  assert.match(service, /sample_ids: phenotypeStringList\(value\.sample_ids\)/);
  assert.match(source, /Manage phenotype data/);
  assert.match(source, /Present features/);
  assert.match(source, /Explicitly absent/);
  assert.doesNotMatch(source, /function PhenotypeSummary/);
  assert.match(styles, /\.phenotype-review-panel/);
});
